use clap::{Parser, Subcommand};
#[cfg(feature = "serve")]
use folio_vitae::logging::init_tracing_with_filter;
use folio_vitae::{AppResult, ResultExt, initialize_project};
#[cfg(feature = "serve")]
use folio_vitae::{app::environment::Environment, load_env_file};
#[cfg(feature = "serve")]
use folio_vitae::{
    config::{DEFAULT_CV_PORT, DEFAULT_MAIN_PORT, ENV_CV_PORT, ENV_MAIN_PORT},
    read_port_from_env, run_servers, run_servers_with_watch,
};
#[cfg(feature = "serve")]
use folio_vitae::{logging::init_tracing, resources::ensure_runtime_assets};
#[cfg(feature = "serve")]
use serde::Serialize;
#[cfg(feature = "serve")]
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
#[cfg(feature = "serve")]
use tracing::warn;
#[cfg(feature = "serve")]
use tracing_subscriber::EnvFilter;

#[derive(Parser)]
#[command(author, version, about = "Run folio-vitae websites in development or production")]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

impl Cli {
    fn command_or_default(self) -> Commands {
        self.command.unwrap_or_else(default_command)
    }
}

#[derive(Subcommand)]
enum Commands {
    /// Initialize a new folio-vitae project in the current directory.
    Init {
        /// Overwrite existing files generated by this command.
        #[arg(long)]
        force: bool,
    },
    /// Run the two websites locally with automatic restart on file changes.
    #[cfg(feature = "serve")]
    Dev {
        /// Port for the main website server (overrides MAIN_PORT).
        #[arg(long, value_parser = clap::value_parser!(u16))]
        main_port: Option<u16>,
        /// Port for the CV website server (overrides CV_PORT).
        #[arg(long, value_parser = clap::value_parser!(u16))]
        cv_port: Option<u16>,
        /// Path to the environment file to load before starting.
        #[arg(long, default_value = ".env", value_name = "PATH")]
        env_file: String,
        /// Host interface to bind the servers to.
        #[arg(long, default_value = "127.0.0.1", value_parser)]
        host: IpAddr,
        /// Suppress non-essential output.
        #[arg(long, conflicts_with = "json")]
        quiet: bool,
        /// Emit machine-readable JSON output.
        #[arg(long, conflicts_with = "quiet")]
        json: bool,
    },
    /// Run the two websites in production mode without file watching.
    #[cfg(feature = "serve")]
    Prod {
        /// Port for the main website server (overrides MAIN_PORT).
        #[arg(long, value_parser = clap::value_parser!(u16))]
        main_port: Option<u16>,
        /// Port for the CV website server (overrides CV_PORT).
        #[arg(long, value_parser = clap::value_parser!(u16))]
        cv_port: Option<u16>,
        /// Path to the environment file to load before starting.
        #[arg(long, default_value = ".env", value_name = "PATH")]
        env_file: String,
        /// Host interface to bind the servers to.
        #[arg(long, default_value = "127.0.0.1", value_parser)]
        host: IpAddr,
        /// Suppress non-essential output.
        #[arg(long, conflicts_with = "json")]
        quiet: bool,
        /// Emit machine-readable JSON output.
        #[arg(long, conflicts_with = "quiet")]
        json: bool,
    },
}

#[tokio::main]
async fn main() -> AppResult<()> {
    match Cli::parse().command_or_default() {
        Commands::Init { force } => init_command(force),
        #[cfg(feature = "serve")]
        Commands::Dev { main_port, cv_port, env_file, host, quiet, json } => {
            serve_command(ServeCommandOptions::new(
                RuntimeMode::Development,
                main_port,
                cv_port,
                env_file,
                host,
                quiet,
                json,
            ))
            .await
        },
        #[cfg(feature = "serve")]
        Commands::Prod { main_port, cv_port, env_file, host, quiet, json } => {
            serve_command(ServeCommandOptions::new(
                RuntimeMode::Production,
                main_port,
                cv_port,
                env_file,
                host,
                quiet,
                json,
            ))
            .await
        },
    }
}

fn init_command(force: bool) -> AppResult<()> {
    initialize_project(force)?;

    println!("Initialized folio-vitae project in current directory.");
    println!("You can now run `folio-vitae dev`.");

    Ok(())
}

#[cfg(feature = "serve")]
struct ServeCommandOptions {
    mode: RuntimeMode,
    main_port: Option<u16>,
    cv_port: Option<u16>,
    env_file: String,
    host: IpAddr,
    quiet: bool,
    json: bool,
}

#[cfg(feature = "serve")]
impl ServeCommandOptions {
    #[allow(clippy::too_many_arguments)]
    fn new(
        mode: RuntimeMode,
        main_port: Option<u16>,
        cv_port: Option<u16>,
        env_file: String,
        host: IpAddr,
        quiet: bool,
        json: bool,
    ) -> Self {
        Self { mode, main_port, cv_port, env_file, host, quiet, json }
    }

    fn output_mode(&self) -> ServeOutputMode {
        if self.json {
            ServeOutputMode::Json
        } else if self.quiet {
            ServeOutputMode::Quiet
        } else {
            ServeOutputMode::Normal
        }
    }
}

#[cfg(feature = "serve")]
async fn serve_command(options: ServeCommandOptions) -> AppResult<()> {
    let output_mode = options.output_mode();

    match output_mode {
        ServeOutputMode::Json | ServeOutputMode::Quiet => {
            init_tracing_with_filter(EnvFilter::new("warn"))?;
        },
        ServeOutputMode::Normal => init_tracing()?,
    }

    ensure_runtime_assets().with_context(|| "preparing embedded assets")?;

    load_env_file(&options.env_file)?;
    let environment = options.mode.environment();

    let main_port = options
        .main_port
        .map(Ok)
        .unwrap_or_else(|| read_port_from_env(ENV_MAIN_PORT, DEFAULT_MAIN_PORT))?;
    let cv_port = options
        .cv_port
        .map(Ok)
        .unwrap_or_else(|| read_port_from_env(ENV_CV_PORT, DEFAULT_CV_PORT))?;

    if !options.host.is_loopback() {
        warn!(
            "Serving local content on a non-loopback interface ({}). Make sure you trust the network.",
            options.host
        );
    }

    let main_addr = SocketAddr::new(options.host, main_port);
    let cv_addr = SocketAddr::new(options.host, cv_port);
    let output =
        ServeOutput { main: format!("http://{main_addr}"), cv: format!("http://{cv_addr}") };

    output.print(output_mode)?;

    match options.mode {
        RuntimeMode::Development => {
            run_servers_with_watch(
                environment,
                options.host,
                main_port,
                cv_port,
                &options.env_file,
            )
            .await?;
        },
        RuntimeMode::Production => {
            let shutdown = async {
                tokio::signal::ctrl_c().await.with_context(|| "listening for shutdown signal")?;
                Ok(())
            };

            run_servers(environment, options.host, main_port, cv_port, shutdown).await?;
        },
    }

    Ok(())
}

fn default_command() -> Commands {
    // Running the binary without a subcommand should feel useful for local development.
    #[cfg(feature = "serve")]
    {
        Commands::Dev {
            main_port: None,
            cv_port: None,
            env_file: ".env".to_string(),
            host: IpAddr::V4(Ipv4Addr::LOCALHOST),
            quiet: false,
            json: false,
        }
    }
    #[cfg(not(feature = "serve"))]
    {
        Commands::Init { force: false }
    }
}

#[cfg(feature = "serve")]
#[derive(Clone, Copy)]
enum RuntimeMode {
    Development,
    Production,
}

#[cfg(feature = "serve")]
impl RuntimeMode {
    fn environment(self) -> Environment {
        match self {
            Self::Development => Environment::Development,
            Self::Production => Environment::Production,
        }
    }
}

#[cfg(feature = "serve")]
#[derive(Clone, Copy)]
enum ServeOutputMode {
    Normal,
    Quiet,
    Json,
}

#[cfg(feature = "serve")]
#[derive(Serialize)]
struct ServeOutput {
    main: String,
    cv: String,
}

#[cfg(feature = "serve")]
impl ServeOutput {
    fn print(&self, mode: ServeOutputMode) -> AppResult<()> {
        match mode {
            ServeOutputMode::Normal => {
                println!("Main: {}", self.main);
                println!("CV: {}", self.cv);
            },
            ServeOutputMode::Json => {
                println!("{}", serde_json::to_string(self)?);
            },
            ServeOutputMode::Quiet => (),
        }

        Ok(())
    }
}
